version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: dbs-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: digital_banking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database-setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banking-network

  # Backend Service
  backend:
    build: ./backend
    container_name: dbs-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/digital_banking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - banking-network

  # Frontend Service
  frontend:
    build: ./frontend
    container_name: dbs-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - banking-network

volumes:
  mysql_data:

networks:
  banking-network:
    driver: bridge 